name: Deploy CloudNexus Frontend & Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

        #SONAR-CUBE

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
           -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         
        #AWS
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::814133038071:role/hello-cloudnexus-github-oidc-role
          aws-region: ap-south-1


      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      # ---------------- FRONTEND ----------------

      - name: Build Frontend Image
        run: |
          docker build -t hello-cloudnexus-frontend ./frontend


      #------------Trivy-------------------------
      
      - name: Scan Frontend Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: hello-cloudnexus-frontend:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      #-----------------------------------------------
    
      - name: Tag Frontend Image
        run: |
          docker tag hello-cloudnexus-frontend:latest \
          ${{ secrets.AWS_ECR_URL }}:frontend

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.AWS_ECR_URL }}:frontend

      # ---------------- BACKEND ----------------

      - name: Build Backend Image
        run: |
          docker build -t hello-cloudnexus-backend ./backend

      #-----------------Trivy_____________________
      
      - name: Scan Backend Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: hello-cloudnexus-backend:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


      - name: Tag Backend Image
        run: |
          docker tag hello-cloudnexus-backend:latest \
          ${{ secrets.AWS_ECR_URL }}:backend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.AWS_ECR_URL }}:backend

      # ---------------- DEPLOY ----------------

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-south-1 | \
            docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}

            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true


            docker pull ${{ secrets.AWS_ECR_URL }}:frontend
            docker pull ${{ secrets.AWS_ECR_URL }}:backend

            docker run -d -p 5000:5000 --name frontend \
            ${{ secrets.AWS_ECR_URL }}:frontend

            docker run -d -p 5001:5001 --name backend \
            ${{ secrets.AWS_ECR_URL }}:backend

