name: Deploy Hello CloudNexus to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t hello-cloudnexus .

      - name: Tag Docker image
        run: |
          docker tag hello-cloudnexus:latest ${{ secrets.AWS_ECR_URL }}

      - name: Push Docker image to ECR
        run: |
          docker push 814133038071.dkr.ecr.ap-south-1.amazonaws.com/hello-cloudnexus:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop cloudnexus-app || true
            docker rm cloudnexus-app || true
            docker pull 814133038071.dkr.ecr.ap-south-1.amazonaws.com/hello-cloudnexus:latest
            docker run -d -p 5000:5000 --name cloudnexus-app \
            814133038071.dkr.ecr.ap-south-1.amazonaws.com/hello-cloudnexus:latest

